# valid colors
COLOR_BLACK        =0
COLOR_WHITE        =1
COLOR_RED          =2
COLOR_CYAN         =3
COLOR_PURPLE       =4
COLOR_GREEN        =5
COLOR_BLUE         =6
COLOR_YELLOW       =7
COLOR_ORANGE       =8
COLOR_BROWN        =9
COLOR_LIGHT_RED    =10
COLOR_DARK_GREY    =11
COLOR_GREY         =12
COLOR_LIGHT_GREEN  =13
COLOR_LIGHT_BLUE   =14
COLOR_LIGHT_GREY   =15
